"""
Pytest configuration for users app tests.

Auto-generated by Autogen CLI.
"""

import pytest
import pytest_asyncio
from sqlalchemy.ext.asyncio import AsyncSession

from tests.conftest import (
    db_session,
    test_client,
    test_user,
    auth_headers,
)
from tests.factories.base_factories import reset_factories


@pytest_asyncio.fixture(autouse=True)
async def setup_test_environment():
    """Setup test environment for each test."""
    # Reset factories before each test
    await reset_factories()
    
    yield
    
    # Cleanup after each test if needed
    pass


@pytest.fixture
def app_name():
    """Fixture providing app name for tests."""
    return "users"


# Import fixtures from the main fixtures module
pytest_plugins = [
    "tests.apps.users.tests.fixtures",
]
