"""
E2E тесты с автоматической генерацией из OpenAPI схемы.

Этот модуль демонстрирует подход "сверху вниз" - сначала проверяем
что вся система работает через E2E, потом разбираемся с unit тестами.
"""

import pytest

from tests.utils_test.api_test_client import AsyncApiTestClient, TestScenarioType


class TestE2EAutoGenerated:
    """E2E тесты с автоматической генерацией из OpenAPI схемы."""

    async def test_auto_generate_all_endpoint_tests(self, api_client: AsyncApiTestClient):
        """
        Автоматически генерирует и проверяет базовые тесты для всех эндпоинтов.

        Это быстрый способ понять состояние всей системы.
        """
        # Загружаем OpenAPI схему
        schema = api_client.load_openapi_schema()

        if not schema:
            pytest.skip("OpenAPI схема недоступна")

        # Генерируем тесты для всех эндпоинтов
        generated_tests = api_client.generate_tests_from_schema()

        print(f"\n🔍 Сгенерировано {len(generated_tests)} автоматических тестов")

        # Группируем тесты по эндпоинтам для анализа
        endpoints_summary = {}

        for test in generated_tests:
            endpoint_key = f"{test.method} {test.endpoint}"
            if endpoint_key not in endpoints_summary:
                endpoints_summary[endpoint_key] = {
                    "success_tests": 0,
                    "validation_tests": 0,
                    "security_tests": 0,
                    "total_confidence": 0.0,
                }

            if "success" in test.test_name.lower():
                endpoints_summary[endpoint_key]["success_tests"] += 1
            elif "validation" in test.test_name.lower():
                endpoints_summary[endpoint_key]["validation_tests"] += 1
            elif "security" in test.test_name.lower():
                endpoints_summary[endpoint_key]["security_tests"] += 1

            endpoints_summary[endpoint_key]["total_confidence"] += test.confidence_score

        # Выводим сводку по эндпоинтам
        print(f"\n📊 Анализ покрытия эндпоинтов:")
        for endpoint, stats in endpoints_summary.items():
            avg_confidence = stats["total_confidence"] / max(
                1, stats["success_tests"] + stats["validation_tests"] + stats["security_tests"]
            )
            print(
                f"  {endpoint}: {stats['success_tests']}✅ {stats['validation_tests']}🔍 {stats['security_tests']}🔒 (уверенность: {avg_confidence:.1%})"
            )

        # Проверяем что у нас есть тесты для основных эндпоинтов
        assert len(generated_tests) > 0, "Не удалось сгенерировать автоматические тесты"

        # Ищем основные Auth и User эндпоинты
        auth_endpoints = [t for t in generated_tests if "auth" in t.endpoint.lower()]
        user_endpoints = [t for t in generated_tests if "user" in t.endpoint.lower()]

        print(f"\n🔐 Auth эндпоинты: {len(auth_endpoints)}")
        print(f"👤 User эндпоинты: {len(user_endpoints)}")

        assert len(auth_endpoints) > 0, "Не найдены Auth эндпоинты в автогенерированных тестах"
        assert len(user_endpoints) > 0, "Не найдены User эндпоинты в автогенерированных тестах"

    async def test_run_critical_endpoint_success_tests(self, api_client: AsyncApiTestClient):
        """
        Запускает автогенерированные success тесты для критических эндпоинтов.

        Если эти тесты проходят, значит основная функциональность работает.
        """
        # Включаем трекинг производительности
        api_client.enable_performance_tracking()

        # Генерируем тесты
        generated_tests = api_client.generate_tests_from_schema()

        if not generated_tests:
            pytest.skip("Автогенерированные тесты недоступны")

        # Фильтруем только success тесты для критических эндпоинтов
        critical_patterns = ["login", "register", "user", "profile", "auth"]
        success_tests = [
            test
            for test in generated_tests
            if "success" in test.test_name.lower()
            and any(pattern in test.endpoint.lower() for pattern in critical_patterns)
            and test.confidence_score > 0.7  # Только высокоуверенные тесты
        ]

        print(f"\n🎯 Запуск {len(success_tests)} критических success тестов...")

        passed_tests = 0
        failed_tests = 0

        async with api_client.test_session(TestScenarioType.E2E):
            for test in success_tests[:10]:  # Ограничиваем первыми 10 для быстроты
                try:
                    # Запускаем автогенерированный тест
                    success = api_client.run_generated_test(test)

                    if success:
                        passed_tests += 1
                        print(f"  ✅ {test.test_name}")
                    else:
                        failed_tests += 1
                        print(f"  ❌ {test.test_name}")

                except Exception as e:
                    failed_tests += 1
                    print(f"  💥 {test.test_name}: {str(e)[:100]}")

        # Получаем метрики производительности
        performance_stats = api_client.get_performance_stats()

        print(f"\n📈 Результаты E2E тестирования:")
        print(f"  Пройдено: {passed_tests}")
        print(f"  Упало: {failed_tests}")
        print(f"  Успешность: {passed_tests / (passed_tests + failed_tests) * 100:.1f}%")

        if performance_stats.get("average_response_time"):
            print(f"  Среднее время ответа: {performance_stats['average_response_time']:.3f}s")
            print(f"  Общее количество запросов: {performance_stats.get('total_requests', 0)}")

        # Если больше 50% тестов проходят, считаем что система в целом работает
        success_rate = passed_tests / (passed_tests + failed_tests) if (passed_tests + failed_tests) > 0 else 0

        if success_rate >= 0.5:
            print(f"\n🎉 E2E тесты показывают что система в целом РАБОТАЕТ! ({success_rate:.1%} success rate)")
            print("💡 Проблемы скорее всего в unit/integration тестах, а не в коде")
        else:
            print(f"\n⚠️  E2E тесты показывают проблемы в системе ({success_rate:.1%} success rate)")
            print("🔧 Нужно исправлять основную функциональность")

        # Не делаем assert чтобы не прерывать тест - нам важна диагностика

    async def test_basic_user_flow_e2e(self, api_client: AsyncApiTestClient, user_factory):
        """
        Базовый E2E тест пользовательского флоу.

        Тестирует создание пользователя → аутентификацию → использование API.
        """
        print(f"\n🚀 Запуск базового пользовательского E2E флоу...")

        # Создаем тестового пользователя через фабрику
        user = await user_factory.create(
            email="e2e_test@example.com", username="e2e_user", is_active=True, is_verified=True
        )

        # Этап 1: Аутентификация
        print(f"  1️⃣ Аутентификация пользователя...")
        auth_user = await api_client.force_auth(user=user)
        assert auth_user.email == "e2e_test@example.com"
        print(f"     ✅ Пользователь аутентифицирован: {auth_user.email}")

        # Этап 2: Проверка доступа к защищенным эндпоинтам
        print(f"  2️⃣ Тестирование защищенных эндпоинтов...")

        # Проверяем профиль пользователя
        try:
            profile_url = api_client.url_for("get_my_profile")  # Исправлено имя route
            response = await api_client.get(profile_url)

            if response.status_code == 200:
                print(f"     ✅ Профиль пользователя доступен")
            else:
                print(f"     ⚠️  Профиль недоступен: {response.status_code}")

        except Exception as e:
            print(f"     💥 Ошибка доступа к профилю: {str(e)[:100]}")

        # Проверяем информацию о пользователе
        try:
            user_info_url = api_client.url_for("get_current_user_info")  # Исправлено имя route
            response = await api_client.get(user_info_url)

            if response.status_code == 200:
                user_data = response.json()
                print(f"     ✅ Информация о пользователе получена: {user_data.get('email', 'N/A')}")
                assert user_data.get("email") == "e2e_test@example.com"
            else:
                print(f"     ⚠️  Информация о пользователе недоступна: {response.status_code}")

        except Exception as e:
            print(f"     💥 Ошибка получения информации: {str(e)[:100]}")

        # Этап 3: Выход из системы
        print(f"  3️⃣ Выход из системы...")
        await api_client.force_logout()

        # Проверяем что защищенные эндпоинты стали недоступны
        try:
            # Повторно получаем URL (на случай если переменная не была инициализирована выше)
            test_url = api_client.url_for("get_current_user_info")
            response = await api_client.get(test_url)
            if response.status_code in [401, 403]:
                print(f"     ✅ После выхода доступ корректно заблокирован")
            else:
                print(f"     ⚠️  После выхода доступ все еще открыт: {response.status_code}")
        except Exception as e:
            print(f"     💥 Ошибка проверки выхода: {str(e)[:100]}")

        print(f"\n🏁 Базовый E2E флоу завершен")

    async def test_api_health_check_e2e(self, api_client: AsyncApiTestClient):
        """
        Проверка здоровья API - базовые эндпоинты должны отвечать.
        """
        print(f"\n🏥 Проверка здоровья API...")

        # Список базовых эндпоинтов для проверки
        health_endpoints = [
            ("/docs", "GET", "Swagger документация"),
            ("/openapi.json", "GET", "OpenAPI схема"),
            ("/", "GET", "Корневой эндпоинт"),
        ]

        healthy_endpoints = 0

        for endpoint, method, description in health_endpoints:
            try:
                response = await api_client.request(method, endpoint)

                if response.status_code < 500:  # Любой не-серверный код это OK
                    healthy_endpoints += 1
                    print(f"  ✅ {description}: {response.status_code}")
                else:
                    print(f"  ❌ {description}: {response.status_code}")

            except Exception as e:
                print(f"  💥 {description}: {str(e)[:50]}")

        health_rate = healthy_endpoints / len(health_endpoints)
        print(f"\n🩺 Здоровье API: {health_rate:.1%} ({healthy_endpoints}/{len(health_endpoints)})")

        # API считается здоровым если базовые эндпоинты отвечают
        assert health_rate >= 0.5, f"API нездоров: только {health_rate:.1%} базовых эндпоинтов работают"
